(function(){'use strict';
const $=id=>document.getElementById(id);
const screens={HOME:[['INICIO','Início']],CAMPANHAS:[['MENSAIS','Campanhas Mensais'],['EXTRAS','Campanhas Extras']],VENDEDORES:[['PARCIAL','Parcial']],TELEVENDAS:[['PARCIAL','Parcial']],POSITIVACOES:[['GERAL','Visão Geral']]};
const users=new Map(),roles=new Set();
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();
const status=(message,error=false)=>{const el=$('feedback');el.textContent=message;el.style.color=error?'#b42318':'#14784a';};
async function api(path,options={}){const response=await fetch(path,{credentials:'include',cache:'no-store',...options});let data={};try{data=await response.json();}catch(_){}if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:'Não foi possível concluir esta operação.');return data;}
function makeChip(label,onRemove){const chip=document.createElement('span');chip.className='chip';chip.append(document.createTextNode(label));const remove=document.createElement('button');remove.type='button';remove.setAttribute('aria-label','Remover '+label);remove.textContent='×';remove.addEventListener('click',onRemove);chip.append(remove);return chip;}
function renderUsers(){$('user-chips').replaceChildren(...[...users.values()].map(u=>makeChip(u.nome+' — '+(u.cargo||u.setor||u.usuario),()=>{users.delete(norm(u.usuario));renderUsers();})));} 
function renderRoles(){$('role-chips').replaceChildren(...[...roles].map(r=>makeChip(r,()=>{roles.delete(r);renderRoles();})));} 
function mode(){return document.querySelector('input[name="mode"]:checked').value;}
function showMode(){$('by-role').classList.toggle('hidden',mode()!=='CARGOS');$('by-user').classList.toggle('hidden',mode()!=='USUARIOS');}
function showScreens(){const opts=screens[$('module').value]||[];$('screen').replaceChildren(...opts.map(([value,label])=>new Option(label,value)));const filter=$('module').value==='TELEVENDAS'&&$('screen').value==='PARCIAL';$('supplier-group').classList.toggle('hidden',!filter);if(!filter)$('supplier').value='';preview();}
function preview(){$('preview-title').textContent=$('title').value.trim()||'Título da notificação';$('preview-message').textContent=$('message').value.trim()||'Sua mensagem aparecerá aqui.';const mod=$('module').selectedOptions[0]?.textContent||'';const tela=$('screen').selectedOptions[0]?.textContent||'';$('preview-destination').textContent=[mod,tela,$('supplier').value.trim()].filter(Boolean).join(' → ');}
let searchSeq=0;
async function search(){const q=$('user-search').value.trim();const seq=++searchSeq;const box=$('suggestions');box.replaceChildren();box.classList.add('hidden');if(q.length<2)return;try{const result=await api('/notificacoes/api/usuarios?q='+encodeURIComponent(q));if(seq!==searchSeq)return;const hits=(result.usuarios||[]).filter(u=>!users.has(norm(u.usuario)));for(const u of hits){const btn=document.createElement('button');btn.type='button';const strong=document.createElement('strong');strong.textContent=u.nome||u.usuario;btn.append(strong,document.createTextNode(' — '+(u.cargo||u.setor||u.usuario)));btn.addEventListener('click',()=>{users.set(norm(u.usuario),u);renderUsers();$('user-search').value='';box.classList.add('hidden');box.replaceChildren();$('user-search').focus();});box.append(btn);}if(!hits.length){const p=document.createElement('p');p.style.padding='8px 12px';p.textContent='Nenhum usuário disponível.';box.append(p);}box.classList.remove('hidden');}catch(e){if(seq===searchSeq)status(e.message,true);}}
async function loadRoles(){try{const result=await api('/notificacoes/api/cargos');$('role').replaceChildren(new Option('Selecione um cargo',''),...(result.cargos||[]).map(r=>new Option(r,r)));}catch(e){status(e.message,true);}}
async function history(){const holder=$('history');holder.textContent='Carregando...';try{const result=await api('/notificacoes/api/historico');holder.replaceChildren();if(!(result.notificacoes||[]).length){holder.textContent='Nenhum aviso publicado nesta central.';return;}for(const item of result.notificacoes){const article=document.createElement('article');const strong=document.createElement('div');strong.style.fontWeight='750';strong.textContent=item.titulo||'Aviso';const detail=document.createElement('small');const d=item.destino||{};detail.textContent=[item.criadoEm,item.criadoPor,[d.modulo,d.tela,d.fornecedor].filter(Boolean).join(' → ')].filter(Boolean).join(' · ');article.append(strong,detail);holder.append(article);}}catch(e){holder.textContent=e.message;}}
document.querySelectorAll('input[name="mode"]').forEach(el=>el.addEventListener('change',showMode));
$('role').addEventListener('change',()=>{if($('role').value){roles.add($('role').value);renderRoles();$('role').value='';}});
$('user-search').addEventListener('input',()=>{clearTimeout(window.__dismepeNotificationSearchTimer);window.__dismepeNotificationSearchTimer=setTimeout(search,250);});
$('module').addEventListener('change',showScreens);$('screen').addEventListener('change',showScreens);
['title','message','supplier'].forEach(id=>$(id).addEventListener('input',preview));
$('refresh').addEventListener('click',history);
$('form').addEventListener('submit',async event=>{event.preventDefault();const send=$('send');const m=mode();if(m==='USUARIOS'&&!users.size)return status('Selecione ao menos um usuário.',true);if(m==='CARGOS'&&!roles.size)return status('Selecione ao menos um cargo.',true);send.disabled=true;status('Salvando a notificação...');try{const data=await api('/notificacoes/api/enviar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({titulo:$('title').value,mensagem:$('message').value,modo:m,usuarios:[...users.values()].map(u=>u.usuario),cargos:[...roles],destino:{modulo:$('module').value,tela:$('screen').value,fornecedor:$('supplier').value.trim()}})});status(data.mensagem||'Aviso salvo.');await history();}catch(e){status(e.message,true);}finally{send.disabled=false;}});
showMode();showScreens();loadRoles();history();
})();